title: Fundamentos de computo musical
logo: /assets/img/error.webp
description: Notas y recursos de la clase. Imparte Dr. Hugo Solís García.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
